### ISSUE TITLE
Update Font family and Theme

### ISSUE THREAD

**Issue by omrsfylmz** [PranavTrip/WeatherReact#21]
Font family and theme a little bit looks old I can improve UI

**Comment by iamvaiibhav19** [comment]
@PranavTrip assign me this issue! I will apply dark and light theme to ui and will. Add new font family

**Comment by PranavTrip** [comment]
> @PranavTrip assign me this issue! I will apply dark and light theme to ui and will. Add new font family

@iamvaiibhav19 already assigned issue #17  to you.
