### ISSUE TITLE
Add some more features like rain %, humidity etc.

### ISSUE THREAD

**Issue by PranavTrip** [PranavTrip/WeatherReact#4]

**Comment by Catzla** [comment]
This is something i'd like to work on, please assign me to this issue if available.

**Comment by PranavTrip** [comment]
> This is something i'd like to work on, please assign me to this issue if available.

Yeah sure @Catzla please go ahead and create a new branch before you start your work. Assigned !

**Comment by omkar342** [comment]
Hello @PranavTrip, I have already understood your project and I would like to contribute to this project. Will you plz assign this to me?

**Comment by PranavTrip** [comment]
> > @iamvaiibhav19 this issue is already assigned. If @Catzla fails I will assign this to you.
> 
> @PranavTrip Okayy! Do let me knoww! I will make it! Till then any issues? Adding dropdowns for search bar? Making Weather app title look attractive? Any Animations?

Will let you know if any idea hits my mind.

**Comment by PranavTrip** [comment]
> > > > @iamvaiibhav19 this issue is already assigned. If @Catzla fails I will assign this to you.
> > > 
> > > 
> > > @PranavTrip Okayy! Do let me knoww! I will make it! Till then any issues? Adding dropdowns for search bar? Making Weather app title look attractive? Any Animations?
> > 
> > 
> > Will let you know if any idea hits my mind.
> 
> Okay! sure

Hey @iamvaiibhav19 want to work on this issue? I can assign this to you please revert ASAP.

**Comment by iamvaiibhav19** [comment]
> > > > > @iamvaiibhav19 this issue is already assigned. If @Catzla fails I will assign this to you.
> > > > 
> > > > 
> > > > @PranavTrip Okayy! Do let me knoww! I will make it! Till then any issues? Adding dropdowns for search bar? Making Weather app title look attractive? Any Animations?
> > > 
> > > 
> > > Will let you know if any idea hits my mind.
> > 
> > Okay! sure
> 
> Hey @iamvaiibhav19 want to work on this issue? I can assign this to you please revert ASAP.

Yes I would Love to work on this issue! Assign it to me!

**Comment by PranavTrip** [comment]
> > > > > > @iamvaiibhav19 this issue is already assigned. If @Catzla fails I will assign this to you.
> > > > > 
> > > > > 
> > > > > @PranavTrip Okayy! Do let me knoww! I will make it! Till then any issues? Adding dropdowns for search bar? Making Weather app title look attractive? Any Animations?
> > > > 
> > > > 
> > > > Will let you know if any idea hits my mind.
> > > 
> > > 
> > > Okay! sure
> > 
> > 
> > Hey @iamvaiibhav19 want to work on this issue? I can assign this to you please revert ASAP.
> 
> Yes I would Love to work on this issue! Assign it to me!

Go ahead, @iamvaiibhav19 I will assign this to you.

**Comment by iamvaiibhav19** [comment]
@PranavTrip can I change background image and UI little bit! Because to add these features I need some space on background image!

**Comment by PranavTrip** [comment]
> @PranavTrip can I change background image and UI little bit! Because to add these features I need some space on background image!

Yeah sure, do whatever changes you want but push the changes only in the 'features' branch.

**Comment by iamvaiibhav19** [comment]
> > @PranavTrip can I change background image and UI little bit! Because to add these features I need some space on background image!
> 
> Yeah sure, do whatever changes you want but push the changes only in the 'features' branch.

Yes Sure!

**Comment by iamvaiibhav19** [comment]
@PranavTrip I am working on adding few features! but this API has limited features and even there are no icons to fetch. So i am using different API which has many features which are really helpful and can tell user about the exact weather details briefly. Is it Okay?

**Comment by iamvaiibhav19** [comment]
@PranavTrip Please review my pull request. Thanks! :)
