### ISSUE TITLE
Add Footer to the Weather React App.

### ISSUE THREAD

**Issue by omkar342** [PranavTrip/WeatherReact#7]
Hi @PranavTrip, I would like to add a responsive footer to your project. I can also add your Social Media handle links in the footer.
If you have any other idea of adding anything to the footer plz share that with me & I would be really grateful if you can assign this to me.

**Comment by PranavTrip** [comment]
Hey @omkar342 instead of a footer I am thinking of adding a dynamic background image according to the weather of that particular city. Like if the weather is sunny the background image must be changed to sun. If you have any doubt feel free to ask.

**Comment by iamvaiibhav19** [comment]
hi @PranavTrip  I would like to contribute to your weather app as I have build one previously. So do you want footer or dynamic background image?

**Comment by PranavTrip** [comment]
> @PranavTrip Just gone through your weather app. As I was trying to give input of any city, as soon as i enter first letter in the search box it gets store in the state 'search' which you have made of searchbox and it starts fetching data for it so it is giving error and is not user friendly. So can i make a button named search which will take whole input from search box and then only it will fetch so it wont be give any error. This is because I am trying to access image icon from the api you are fetching. so do let me know

I will create a new issue and assign it to you. Is it okay ?
